project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Spring 2024"
  author:
    - name: Jun Yan and Students in Spring 2024:
    - name: Matt Elliott, Joshua Lee, Olivia Massad
    - name: Leon Nguyen, Pratham Patel, Isabelle Perez
    - name: William Qualls, Weijia Wu, Vincent Xie
    - name: Emmanuel Yankson, Xingye Zhang
  date: today

  sidebar:
    logo: images/ids-s24.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - git.qmd
    - quarto.qmd
    - python.qmd
    - import.qmd
    - communication.qmd
    - eda.qmd
    - visualization.qmd
    - statsmod.qmd
    - supervised.qmd
    - advanced.qmd
    - exercises.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt

execute:
  freeze: auto
