project:
  type: book

book:
  title: "Introduction to Data Science"
  subtitle: "STAT 3255/5255 @ UConn, Spring 2024"
  author:
    - name: Jun Yan and Students in Spring 2024
    - name: Matt Elliott
    - name: Joshua Lee
    - name: Olivia Massad
    - name: Leon Nguyen
    - name: Pratham Patel
    - name: Isabelle Perez
    - name: Weijia Wu
    - name: Vincent Xie
    - name: Xingye Zhang
    - name: William Qualls
  date: today

  sidebar:
    logo: images/ids-s24.png
  
  chapters:
    - index.qmd
    - intro.qmd
    - git.qmd
    - quarto.qmd
    - python.qmd
    - import.qmd
    - webscraping.qmd
    - communication.qmd
    - eda.qmd
    - visualization.qmd
    - statsmod.qmd
    - supervised.qmd
    - exercises.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt

execute:
  freeze: auto
